In [2]:
!pip install -U torch torchvision

Requirement already up-to-date: torch in /usr/local/lib/python3.6/dist-packages (1.4.0)
Requirement already up-to-date: torchvision in /usr/local/lib/python3.6/dist-packages (0.5.0)


In [3]:
!pip install watermark

In [0]:
%load_ext watermark

In [5]:
%watermark -v -p numpy,torch

CPython 3.6.9
IPython 5.5.0

numpy 1.17.5
torch 1.4.0


# PyTorch ❤️ NumPy

Do you know NumPy? If you do, learning PyTorch will be a breeze! If you don't, prepare to learn the skills that will guide you on your journey Machine Learning Mastery!

Let's start with something simple:

In [0]:
import torch
import numpy as np

In [7]:
a = np.array([1, 2])
b = np.array([8, 9])

c = a + b
c

array([ 9, 11])

Adding the same arrays with PyTorch looks like this:

In [8]:
a = torch.tensor([1, 2])
b = torch.tensor([8, 9])

c = a + b
c

tensor([ 9, 11])

Fortunately, you can go from NumPy to PyTorch:

In [9]:
a = torch.tensor([1, 2])

a.numpy()

array([1, 2])

 and vice versa:

In [10]:
a = np.array([1, 2])
torch.from_numpy(a)

tensor([1, 2])

The good news is that the conversions incur almost no cost on the performance of your app. The NumPy and PyTorch store data in memory in the same way. That is, PyTorch is reusing the work done by NumPy.

# Tensors

Tensors are just n-dimensional number (including booleans) containers. You can find the complete list of supported data types at [PyTorch's Tensor Docs](https://pytorch.org/docs/stable/tensors.html).

So, how can you create a Tensor (try to ignore that I've already shown you how to do it)?



In [11]:
torch.tensor([[1, 2], [2, 1]])

tensor([[1, 2],
        [2, 1]])

You can create a tensor from floats:

In [12]:
torch.FloatTensor([[1, 2], [2, 1]])

tensor([[1., 2.],
        [2., 1.]])

Or define the type like so:

In [15]:
torch.tensor([[1, 2], [2, 1]], dtype=torch.bool)

tensor([[True, True],
        [True, True]])

You can use a wide range of factory methods to create Tensors without manually specifying each number. For example, you can create a matrix with random numbers like this: 

In [17]:
torch.rand(3, 2)

tensor([[0.5853, 0.7024],
        [0.5224, 0.3153],
        [0.9657, 0.1873]])

Or one full of ones:

In [18]:
torch.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

# Running on GPU

# Common Issues