In [2]:
!pip install -U torch torchvision

Requirement already up-to-date: torch in /usr/local/lib/python3.6/dist-packages (1.4.0)
Requirement already up-to-date: torchvision in /usr/local/lib/python3.6/dist-packages (0.5.0)


In [5]:
!pip install watermark

In [0]:
%load_ext watermark

In [11]:
%watermark -v -p numpy,torch

CPython 3.6.9
IPython 5.5.0

numpy 1.17.5
torch 1.4.0


# PyTorch ❤️ NumPy

Do you know NumPy? If you do, learning PyTorch will be a breeze! If you don't, prepare to learn the skills that will guide you on your journey Machine Learning Mastery!

Let's start with something simple:

In [0]:
import torch
import numpy as np

In [4]:
a = np.array([1, 2])
b = np.array([8, 9])

c = a + b
c

array([ 9, 11])

Adding the same arrays with PyTorch looks like this:

In [12]:
a = torch.tensor([1, 2])
b = torch.tensor([8, 9])

c = a + b
c

tensor([ 9, 11])

Fortunately, you can go from NumPy to PyTorch:

In [14]:
a = torch.tensor([1, 2])

a.numpy()

array([1, 2])

 and vice versa:

In [15]:
a = np.array([1, 2])
torch.from_numpy(a)

tensor([1, 2])

# Tensors

# Running on GPU

# Common Issues